// SETTINGS CONSTANTS
export const LOADING = 'LOADING';
export const LOGO_BG = 'LOGO_BG';
export const NAVBAR_BG = 'NAVBAR_BG';
export const SIDEBAR_BG = 'SIDEBAR_BG';
export const THEME = 'THEME';
export const DIRECTION = 'DIRECTION';
export const SIDEBAR_POSITION = 'SIDEBAR_POSITION';
export const HEADER_POSITION = 'HEADER_POSITION';
export const LAYOUT = 'LAYOUT';
export const SIDEBAR_TYPE = 'SIDEBAR_TYPE';

// AUTH CONSTANTS
export const SAVE_TOKEN = 'SAVE_TOKEN';
export const CHECK_AUTH = 'CHECK_AUTH';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_ME = 'GET_ME';
export const GET_ME_SUCCESS = 'GET_ME_SUCCESS';
export const GET_ME_FAILED = 'GET_ME_FAILED';
export const EMAIL_CONFIRMATION = 'EMAIL_CONFIRMATION';


// PRODUCT CONSTANTS
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const GET_FEATURED_PRODUCT = 'GET_FEATURED_PRODUCT';
export const UPDATE_FEATURED_PRODUCT = 'UPDATE_FEATURED_PRODUCT';
export const GET_TOPSELL_PRODUCT = 'GET_TOPSELL_PRODUCT';
export const UPDATE_TOPSELL_PRODUCT = 'UPDATE_TOPSELL_PRODUCT';
export const GET_ONSALE_PRODUCT = 'GET_ONSALE_PRODUCT';
export const UPDATE_ONSALE_PRODUCT = 'UPDATE_ONSALE_PRODUCT';
export const FETCH_HOME_PRODUCT = 'FETCH_HOME_PRODUCT';
export const SELECT_PRODUCT = 'SELECT_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ONE_DETAIL = 'ONE_DETAIL';
export const ADD_TO_ORDER_CART = 'ADD_TO_ORDER_CART';
export const ADD_LIST = 'ADD_LIST';
export const LIST_PRODUCT = 'LIST_PRODUCT';
export const SELECT_LIST_NAME = 'SELECT_LIST_NAME';
export const SHIP_DETAIL = 'SHIP_DETAIL';
export const GET_ORDER_PRODUCT= 'GET_ORDER_PRODUCT';
export const UPDATE_ALL_PRODUCT = 'UPDATE_ALL_PRODUCT';
export const ALL_CATEGORY = 'ALL_CATEGORY';
export const UPDATE_PRICE = 'UPDATE_PRICE';
export const UPDATE_SEARCH_VALUE_TC = 'UPDATE_SEARCH_VALUE_TC';
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT';
export const UPDATE_SEARCH_VALUE_C = 'UPDATE_SEARCH_VALUE_C';
export const UPDATE_SEARCH_VALUE_B = 'UPDATE_SEARCH_VALUE_B';
export const FIRST_CATEGORIES = "FIRST_CATEGORIES";
export const SECOND_CATEGORIES = "SECOND_CATEGORIES";
export const THIRD_CATEGORIES = "THIRD_CATEGORIES";
export const UPDATE_SEARCH_VALUE_CON = 'UPDATE_SEARCH_VALUE_CON';
export const SORT_PRODUCT = 'SORT_PRODUCT';
export const SEARCH_NAV_LIST = 'SEARCH_NAV_LIST';
export const PAGE_NUMBER = 'PAGE_NUMBER';
export const PAGE_PRODUCT = 'PAGE_PRODUCT';
export const SEARCHED_NUMBER = 'SEARCHED_NUMBER';
